# Generated by Django 4.1.5 on 2023-02-02 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nic_app', '0003_alter_instrument_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='images/default.jpg', upload_to='images/projects/')),
            ],
        ),
        migrations.AlterField(
            model_name='instrument',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='images/instruments/'),
        ),
    ]
