# Generated by Django 4.1.5 on 2023-02-05 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nic_app', '0004_project_alter_instrument_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ongoing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='images/default.jpg', upload_to='images/ongoing/')),
            ],
        ),
        migrations.DeleteModel(
            name='Instrument',
        ),
        migrations.AddField(
            model_name='project',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
