# Generated by Django 4.1.5 on 2023-02-10 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nic_app', '0008_alter_cart_user_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
